### ISSUE TITLE
Errors after requesting feedback

### ISSUE THREAD

**Issue by Sidragon123** [buildingu/Building-u-feedback#38]
**Describe the bug**
Once a feedback request is made and the user navigates to the 'Feedback Requests' tab, it throws an error 403 and says that the user does not have access and may have been logged out. However, upon trying to log back in with the same credentials, it throws another error and does not login. Signing up with the same credentials also does not work.

**To Reproduce**
1. Submit a Feedback Request
2. Go to 'Feedback Requests'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 125

**Additional context**

**Comment by gbudjeakp** [comment]
So I tried recreating this error but to no avail. It could be that during the time of your testing, the server was done or pre one of the hotfixes I merged. (There's some improvements I need to make with our CD pipeline to sort that out) I was able to submit a request and see it in the feedback request tab. Maybe try again later and see if that is still an issue. 

![Screenshot 2024-07-08 004940](https://github.com/buildingu/Building-u-feedback/assets/61554248/b15cf8db-1389-486a-8aef-e1ce504c6e12)

**Comment by Sidragon123** [comment]
Tried to login now but it still isn't letting me login with my credentials. Won't let me sign up with those again either. 

Edit: Not able to sign up with new credentials either

**Comment by gbudjeakp** [comment]
Okay so I think the issue is with the server, it keeps shutting down, I'll look into it. Thanks

**Comment by gbudjeakp** [comment]
So this should no longer be an issue. We've moved to a different server and things seem to be working fine. Feel free to reopen issue if you see it persisting and add more details to the issue like the browser you are using etc
